// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AlgoCryptoPayment","status":true,"description":"Algo Cryptocurrency payment gateway","parameters":{"BlockchainRPC":"https://bsc-dataseed.binance.org/","StorePrivateVariableID":"5"}},
{"name":"RS_InputDialog","status":true,"description":"This plugin allows you to display Text Edit Box on the screen. <RS_InputDialog>","parameters":{"textBox Width":"488","textBox Height":"36","variable ID":"3","debug":"false","Text Hint":"Please enter the value...","direction":"ltr","Max Length":"255","Style":"","CSS":"\"\"","Button Name":"","Ok":"OK","Cancel":"Cancel","Position":"center"}}
];
